### ISSUE TITLE
Errors when trying to upgrade Dragon Armour with it's LAST remaining points

### ISSUE THREAD

**Issue by QuantumZizo** [Joh0210/DragonMagicAndRelics#10]
Minecraft 1.20.1, MNA 3.0.0.1, DMNR 3.1.8

It is as the title states. When trying to upgrade a piece of upgrade supporting equipment, if that upgrade would consume the all of the remaining points _exactly_, the upgrade supposedly fails (even if executed by command where "force" is false) even though the points remaining are the exact needed. I cannot pinpoint what exactly causes this bug, but here are my theories around it:
- Using the command to add an upgrade that uses all the points _in one go_ does not cause this bug
- If the container was already used up/upgraded to some extent, adding an upgrade which consumes the remaining points exactly will fail.

Here are two reproducible scenarios used to determine those:
- Use the command '/dmnr addUpgrade "dmnr:armorupgrade/damage_resistance" 2 false' to infuse two levels of Damage Resistance (8 points per level) into a Ring of Power; the level 2 Damage Resistance uses 16 points total (RoP capacity is 16) and succeeds to infuse.
- Use the command '/dmnr addUpgrade "dmnr:armorupgrade/damage_resistance" 1 false' to infuse 1 level of Damage Resistance to the Ring of Power, then use the command in scenario one to bring it to level two; the second time will fail to infuse even though there are still enough points to accommodate for the second level like in scenario one.

In the first example, the upgrades were infused and the points were used from 16 -> 0 all in one go (success), whereas in the second example the only difference was the infusing being split into two steps, resulting mysteriously in a fail.

Let me know if there are any more details surrounding my setup to aid you.

**Comment by QuantumZizo** [comment]
Edited for better examples.

**Comment by Joh0210** [comment]
Hey, thank you very much for reporting the error ^^
And thank you for your reproduction notes and for specifying the versions! That's very helpful! 

I'm sorry about the late Fix. Had a lot to do in my private life and didn't really get to modding.
No matter what, the bug is fixed. I'll take care of a few more and then upload the new version tomorrow or monday.

If you're interested, the bug arose because I made a typo (`<` instead of `<=`)
