### ISSUE TITLE
Crash with Dynamic FPS on 1.20.1 Forge

### ISSUE THREAD

**Issue by Alexander317** [Joh0210/DragonMagicAndRelics#13]
https://mclo.gs/NDD2wA3 - crash report
https://mclo.gs/i12mA7R - latest log

Fabric launcher version - 0.15.11
Using Modrinth launcher
All mods have the latest version

**Comment by Alexander317** [comment]
Also crashes with REI:
https://mclo.gs/EIYNuGD - crash report
https://mclo.gs/F85YsQQ - latest log

**Comment by Joh0210** [comment]
The game crashes because of `Dragon Magic and Relics` when one of these mods is installed? 
(Aka: If DM&R is not installed, will the game work?)

**Comment by Alexander317** [comment]
Yes, if DM&R is not installed, the game will work perfectly fine

**Comment by Joh0210** [comment]
Okay, thx ^^
The game crashes immediately when starting?
Do you have a list of installed mods?

**Comment by Alexander317** [comment]
The game crashes right before loading into the main menu in both scenarios.

Modlist with REI: architectury api, caelus api, cloth config api, curios api, mana and artifice, DM&R and REI itself

Modlist with Dynamic FPS: caelus api, cloth config api, curios api, mana and artifice, DM&R and Dynamic FPS itself

**Comment by Alexander317** [comment]
Update: I figured out why the game was crashing, geckolib was missing from my modlist. I'm sorry for the confusion and I will close this issue

**Comment by Joh0210** [comment]
Oh no problem. Glad you were able to solve your problem ^^
