### ISSUE TITLE
Void Charm Delayed Teleport Death

### ISSUE THREAD

**Issue by celestmia** [Joh0210/DragonMagicAndRelics#15]
The void charm teleports the player to their bed when they would be put under 5 hearts of health (also canceling the instance of damage), but because it uses mana and artifice's `TeleportHelper.teleportEntity` method, which does a delayed teleport 2 seconds later, the player can die from further void damage during that delay. Maybe in the past the method used instantly teleported the player?

**Comment by Joh0210** [comment]
Thx, fixed it :) [3.1.11](https://github.com/Joh0210/DragonMagicAndRelics/commit/5d1dbfebc81efcf7a197630ea17c8f9d07d965b3)
