### ISSUE TITLE
Dragon Mage Armor unable to support flight obtained differently without the Fly Glyph Upgrade.

### ISSUE THREAD

**Issue by EpikDisko** [Joh0210/DragonMagicAndRelics#3]
Info:
Any other source of flight, including Mist Form is disabled while wearing a full set of Dragon Mage Armor. (In my case, it's Abyssal.)

Steps to Reproduce:
1: Wear a full set of Dragon Mage Armor that doesn't have Fly upgrade in it.
2: Get any source of flight from another mod or use Mist Form

**Comment by EpikDisko** [comment]
Update: Having Fly 1 consumes mana with Mist Form

**Comment by Joh0210** [comment]
[Commit Link](https://github.com/Joh0210/DragonMagicAndRelics/commit/bdbdc163ebacacdd6613f6ad80c29339fec5b7c5)
