### ISSUE TITLE
update for new Mana and Artifice version 1.20.1-3.0.0.5

### ISSUE THREAD

**Issue by border999** [Joh0210/DragonMagicAndRelics#9]
https://gist.github.com/border999/3c3102eaf42369b8b76c3f3daca89e0f

**Comment by Joh0210** [comment]
Thanks for the info and the log. Fixed it ^^
(DM&R Version [3.1.5](https://github.com/Joh0210/DragonMagicAndRelics/commit/c31efca5004c172618a2a3754f897af906f5390a))
